### ISSUE TITLE
create template repository and update links to hard-coded codeblocks

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubDocs#6]
e.g. in model-metadata.md, pointers could be used.

**Comment by mzorn-58** [comment]
Looks like template repo is in development.  Not sure what pointers mean.

Link to epiforecasts broken.
![image](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/assets/66443989/07faac43-abac-4afc-963b-19019fa71e18)

**Comment by nickreich** [comment]
I think the link to epiforecasts won't work inside that panel, but the link does work if you cut and paste.

to clarify the suggestion here, maybe once an example hub exists, we could add links to the model-metadata schema file for the hub as well as some example files. related to https://github.com/Infectious-Disease-Modeling-Hubs/example-simple-forecast-hub/issues/5

**Comment by micokoch** [comment]
In #91 I used the template metadata schema file from the Example Complex Forecast Hub, because I couldn't find one for the Example Simple Forecast Hub. I created a json file with the optional additional metadata fields, and in addition to the ones that were listed previously, I added those that were in the [last `model-schema` that was used](https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/main/v0.0.0.9/model-schema.json), but were not in the Example Complex Forecast Hub schema. I deleted the YAML versions of the JSON files, following Harry's issue (#33).

I hope this is enough, but please re-open the issue if there are additional fixes needed.
