### ISSUE TITLE
Add link to vignette

### ISSUE THREAD

**Issue by mzorn-58** [Infectious-Disease-Modeling-Hubs/hubDocs#65]
"Using the modeling hubs" - the vignette link goes to the source for the vignette. It should probably link to a PDF/html version. _Note: Lucie said she will update it as soon as the hubVis is running._

**Comment by LucieContamin** [comment]
Hi, if we are talking about the vignette in the example-complex-scenario-hub, I did a quick update and generate a HTML version it [here](https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub/blob/main/articles/example_workflow.html)
The vignette is very generic and probably need more text, I will open an issue to work on it

**Comment by micokoch** [comment]
I copied the page directly to the hubDocs repo, because the [GitHub html preview](https://htmlpreview.github.io/?https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub/blob/main/articles/example_workflow.html) doesn't display plots or outputs correctly. I only mention this because if the vignette is updated, it has to be manually copied to the supplemental folder (in HubDocs). Until that time, this issue is resolved.

**Comment by micokoch** [comment]
Note: this is still not working, as it is downloading the html file rather than displaying it. I will work on it tomorrow.

**Comment by LucieContamin** [comment]
I can also try to output in PDF if that help

**Comment by LucieContamin** [comment]
I updated the vignette and changed the plot to a static version instead of Plotly (that might help). I also generated both HTML and PDF format

**Comment by micokoch** [comment]
I finally fixed this. We can close this issue.
