### ISSUE TITLE
hubDocs website - dark theme difficult to read

### ISSUE THREAD

**Issue by LucieContamin** [Infectious-Disease-Modeling-Hubs/hubDocs#87]
All the schemas on the Hub configuration files are difficult to read in the "dark" version of the website, it seems like the background is change to gray but the font is still gray too. Would it be possible to either change the background/font color for the "dark" version of the schema or maybe force them in a "light" version.

Thanks

**Comment by micokoch** [comment]
Hi Lucie! I fixed this by keeping the schema in the "light version" colors. Otherwise I would have had to change all of the text colors. The problem is json files have their own css, as I learned after much tinkering. You can see the changes in [PR#88](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/pull/88).
